Overdose-Prevention-Solution-Accelerator-main/Overdose-Accelerator-Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using OverdoseAcceleratorWeb.Models;
using System.Diagnostics;

namespace OverdoseAcceleratorWeb.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Overdose-Prevention-Solution-Accelerator-main/Overdose-Accelerator-Web/Controllers/OverdoseMapController.cs
using Microsoft.AspNetCore.Mvc;

namespace OverdoseAcceleratorWeb.Controllers
{
    public class OverdoseMapController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Overdose-Prevention-Solution-Accelerator-main/Overdose-Accelerator-Web/Controllers/OverdoseQuestionnaireController.cs
using Microsoft.AspNetCore.Mvc;
using OverdoseAcceleratorWeb.Models;
using Newtonsoft.Json;
using System.Text;
using Microsoft.Extensions.Options;
using NuGet.Protocol;

namespace OverdoseWebAccelerator.Controllers
{
    public class OverdoseQuestionnaireController : Controller
    {
        private readonly ILogger<OverdoseQuestionnaireController> _logger;
        private readonly FormDictionaries _formDictionaries;
        private readonly WebServiceUrl _webservice; 

        public OverdoseQuestionnaireController(IOptions<FormDictionaries> formDictionaries, IOptions<WebServiceUrl> webservice,  ILogger<OverdoseQuestionnaireController> logger)
        {
            _logger = logger;
            _formDictionaries = formDictionaries.Value;
            _webservice = webservice.Value;
        }
        [HttpGet]
        public IActionResult Index()
        {
            var questionnaire = new QuestionnaireModel();
            questionnaire.LoadDictionaries(_formDictionaries);
            return View(questionnaire);
        }

        [HttpPost]
        public async Task<IActionResult> Results(QuestionnaireModel model)
        {
            var overdoseResult = new OverdoseResult(); 
            
            try
            {
                var url = _webservice.url + _webservice.token;
                var json = JsonConvert.SerializeObject(model.Questionnaire);
                var client = new HttpClient();
                var content = new StringContent(json, Encoding.UTF8, "application/json");
                var result = await client.PostAsync(url, content);
                if (result.IsSuccessStatusCode)
                {
                    if (result.Content is object) 
                    {
                        try
                        {
                            var resultStr = await result.Content.ReadAsStringAsync(); 
                            overdoseResult = JsonConvert.DeserializeObject<OverdoseResult>(resultStr);
                        }
                        catch (JsonReaderException)
                        {
                            _logger.LogError("Invalid JSON.");
                        }
                    }
                    else
                        _logger.LogError("HTTP Response was invalid and cannot be serialized.");
                }   
                else
                  _logger.LogError("The web service did not return a successful return.");
            }
            catch (Exception e)
            {
                _logger.LogError("There was an error trying to get information from the web service" + e.Message);
                throw;
            }

            return View(overdoseResult); 
        }
    }
}   

Overdose-Prevention-Solution-Accelerator-main/Overdose-Accelerator-Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<link rel="stylesheet" href="/css/homepage.css" />

<div class="grid_container">
  <div class="top_container">
    <h1>Opioid Risk Assessment Tool</h1>
    <p>
       <span>This tool is a resource to help communities and care providers gain insight on opioid use in communities and the risks associated with prescribing opioid-based medication.</span>
        <br/>
        <br/>
       <span>If you are a care provider and would like to fill out the risk assessment questionnaire on behalf of a patient, please select<b> “Start Risk Assessment”</b></span>
        <br/>
        <br/>
      <span> If you are a community member and would like to view how opioid overdoses have affected your region, please select <b>“View Social Determinant Impact Map”</b></span>
    </p>
  </div>
  
  <div class="left_container" id="quest">
    <a class="card" id="FormButtonBkg" asp-area="" asp-controller="OverdoseQuestionnaire" asp-action="Index">
        <div class="card_text">
            <svg class="svg_icon" width="80px" height="80px" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M12 2v6a2 2 0 0 0 2 2h4.92c-.596.22-1.144.554-1.558.97l-6.05 6.092a2.815 2.815 0 0 0-.728 1.279l-.525 2.03A2.082 2.082 0 0 0 10.3 22H5.5A1.5 1.5 0 0 1 4 20.5v-17A1.5 1.5 0 0 1 5.5 2H12Z"/><path d="M13.5 2.5V8a.5.5 0 0 0 .5.5h5.5l-6-6ZM12.196 17.572l5.902-5.902a2.285 2.285 0 1 1 3.233 3.232l-5.903 5.902a2.684 2.684 0 0 1-1.247.707l-1.831.457a1.087 1.087 0 0 1-1.318-1.318l.457-1.83c.118-.473.362-.904.707-1.248Z"/></svg>
            <h3>Start Risk Assessment</h3>
        </div>
     </a>       
  </div>
      
  <div class="right_container">
    <a class="card" id="MapButtonBkg" asp-area="" asp-controller="OverdoseMap" asp-action="Index">
      <div class="card_text">
          <svg class="svg_icon" width="80px" height="80px" fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path d="M8.5 4.358v12.465l-4.32 3.038a.75.75 0 0 1-1.174-.509l-.007-.104V8.615a.75.75 0 0 1 .238-.548l.08-.065L8.5 4.358Zm12.494.29.007.104v10.633a.75.75 0 0 1-.238.548l-.08.065L15.5 19.64V7.174l4.32-3.035a.75.75 0 0 1 1.174.509ZM10 4.359l4 2.812v12.467l-4-2.814V4.359Z"/></svg>
          <h3>View Social Determinant Impact Map</h3>
      </div>
    </a>
  </div>
</div>